{% set version = '3.0.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-supernova
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/supernova_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/supernova/supernova_{{ version }}.tar.gz
  sha256: f2d6649fc0674cd166b9aec34b30163517abea2f682061736e88715d37b09693

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-pillar >=1.5.0
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-vctrs
  run:
    - r-base
    - r-cli
    - r-pillar >=1.5.0
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-vctrs

test:
  commands:
    - $R -e "library('supernova')"           # [not win]
    - "\"%R%\" -e \"library('supernova')\""  # [win]

about:
  home: https://github.com/UCLATALL/supernova
  license: GPL-3.0-or-later
  summary: |
    Produces ANOVA tables in the format used by Judd, McClelland, and Ryan (2017, ISBN:
    978-1138819832) in their introductory textbook, Data Analysis. This includes proportional
    reduction in error and formatting to improve ease the transition between the book
    and R.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
# Type: Package
extra:
  recipe-maintainers:
    - conda-forge/r
    - adamblake
